services:
  db:
    image: postgis/postgis:16-3.4
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
    volumes:
      - ./infra/journal/postgres_data:/var/lib/postgresql/data
      - ./infra/conf/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./ddl:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: test_local
      POSTGRES_USER: test_local
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5510"
